### ISSUE TITLE
support string as parameter in version 0.2.0

### ISSUE THREAD

**Issue by ghost** [egomobile/api-log#4]
@zulfiqarjunejo @ekmobile 

many users simply want to use

```typescript
log.info("my message")
```

instead of

```typescript
log.info({
    message: 'my message',
    details: 'details should be optional here'
})
```

i my opinion:

- `details` should be optional
- if i submit a string only, it should be converted to an object automatically, means

`my message`

becomes

```json
{
  "message": "my message"
}
```

**Comment by zulfiqarjunejo** [comment]
If `my message` become `{
    "message": "my message"
}` then we need to address if details will become optional only in api-log package or also in the REST endpoint?
